source "https://rubygems.org"

gem "metanorma-cli", git: "https://github.com/metanorma/metanorma-cli"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso"
gem "metanorma-ogc", git: "https://github.com/metanorma/metanorma-ogc"
gem "metanorma-csand", git: "https://github.com/metanorma/metanorma-csand"
gem "metanorma-m3d", git: "https://github.com/metanorma/metanorma-m3d"
gem "isodoc", git: "https://github.com/metanorma/isodoc"
gem "html2doc", git: "https://github.com/metanorma/html2doc"
# gem "metanorma-ogc", path: "../metanorma-ogc"
