= OGC Policy sample in Metanorma: Technical Committee Policies and Procedures

This work item belongs to OGC TC.

image:https://github.com/metanorma/ogc-tcpnp/workflows/generate/badge.svg["Build Status", link="https://github.com/metanorma/ogc-tcpnp/actions?query=workflow%3Agenerate"]
image:https://github.com/metanorma/ogc-tcpnp/workflows/docker/badge.svg["Docker Build Status", link="https://github.com/metanorma/ogc-tcpnp/actions?query=workflow%3Adocker"]

This document is available in its rendered forms here:

* https://metanorma.github.io/ogc-tcpnp/[OGC Policy: Technical Committee Policies and Procedures (HTML)]

Because of all this, there is no need to build the document on your own, but if you wish to do so, this is how it can be done:

== Fetching the document

[source,sh]
----
git clone https://gitlab.com/metanorma/ogc-tcpnp/
----

== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* OGC XML (https://github.com/metanorma/metanorma-model-ogc) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open ogc-*.html
----

