
[[what-is-a-consortium]]
== What is a Consortium?

A broad definition of a consortium is: a combination or group of organizations formed to undertake a common objective that is beyond the resources or capabilities of any single organization. The OGC was formed to provide a collaborative, consensus forum for the discussion and resolution of interoperability issues in the geospatial domain. The work of the consortium is based on volunteerism.

More specifically in the standards area, a consortium has the following characteristics:

* May or may not have been accredited by any national or global entity;
* Is usually (but not always) international in membership and objectives;
* May have a very narrow or a broad mission (but still generally within a single focus area);
* Has as its primary goal(s) the creation and/or promotion of international standards (most commonly in the IT area);
* Creates what would be acknowledged to be "open" standards made available on Reasonable and Non-Discriminatory (<<term-rand>>) terms; and
* May engage in additional activities, such as the creation of white papers, training and certification, but which rarely becomes a "trade association" in the non-tax sense.

The OGC is defined as a Voluntary Consensus Standards Organization (<<term-vcso>>).
